In [1]:
import numpy as np

# -----------------------------------------------------------
# SAME DATASET AS THE MANUAL EXAMPLE
# -----------------------------------------------------------
C1 = np.array([[4, 2],
               [2, 4],
               [2, 3]])

C2 = np.array([[7, 8],
               [8, 8],
               [9,10]])

X = np.vstack((C1, C2))   # all samples
y = np.array([0]*3 + [1]*3)

In [2]:
X

array([[ 4,  2],
       [ 2,  4],
       [ 2,  3],
       [ 7,  8],
       [ 8,  8],
       [ 9, 10]])

In [3]:
y

array([0, 0, 0, 1, 1, 1])

In [4]:
classes = np.unique(y)
d = X.shape[1]   # number of features

In [7]:
# -----------------------------------------------------------
# STEP 1: Compute Class Means
# -----------------------------------------------------------
mean1 = np.mean(C1, axis=0)
mean2 = np.mean(C2, axis=0)
overall_mean = np.mean(X, axis=0)

print("Mean of Class 1:", mean1)
print("Mean of Class 2:", mean2)
print("Overall Mean:", overall_mean)

Mean of Class 1: [2.66666667 3.        ]
Mean of Class 2: [8.         8.66666667]
Overall Mean: [5.33333333 5.83333333]


In [8]:
# -----------------------------------------------------------
# STEP 2: Compute Within-Class Scatter SW
# -----------------------------------------------------------
SW = np.zeros((d, d))

for C, mean_vec in zip([C1, C2], [mean1, mean2]):
    for x in C:
        diff = (x - mean_vec).reshape(d, 1)
        SW += diff @ diff.T

print("\nWithin-Class Scatter SW:\n", SW)


Within-Class Scatter SW:
 [[4.66666667 0.        ]
 [0.         4.66666667]]


In [13]:
diff

array([[2.66666667],
       [2.83333333]])

In [9]:
# -----------------------------------------------------------
# STEP 3: Compute Between-Class Scatter SB
# -----------------------------------------------------------
SB = np.zeros((d, d))

for C, mean_vec in zip([C1, C2], [mean1, mean2]):
    Ni = C.shape[0]
    diff = (mean_vec - overall_mean).reshape(d, 1)
    SB += Ni * (diff @ diff.T)

print("\nBetween-Class Scatter SB:\n", SB)


Between-Class Scatter SB:
 [[42.66666667 45.33333333]
 [45.33333333 48.16666667]]


In [14]:
# -----------------------------------------------------------
# STEP 4: Compute LDA Direction
# -----------------------------------------------------------
SW_inv = np.linalg.inv(SW)
mean_diff = (mean1 - mean2).reshape(d, 1)

w = SW_inv @ mean_diff
w = w / np.linalg.norm(w)  # normalize for comparison

print("\nLDA Direction Vector w:\n", w)


LDA Direction Vector w:
 [[-0.6853647 ]
 [-0.72819999]]


In [15]:
# -----------------------------------------------------------
# STEP 5: Project Data onto LDA Direction
# -----------------------------------------------------------
X_lda = X @ w

print("\nLDA Projected Values:\n", X_lda)


LDA Projected Values:
 [[ -4.19785878]
 [ -4.28352937]
 [ -3.55532938]
 [-10.62315283]
 [-11.30851753]
 [-13.45028222]]


# From Sklearn